import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url(),
    DATABASE_URL_UNPOOLED: z.string().url().optional(),
    NEXTAUTH_SECRET: z.string().min(16).optional(),
    AUTH_SECRET: z.string().min(16),
    NEXTAUTH_URL: z.string().url().optional(),
    R2_ACCOUNT_ID: z.string().min(1).optional(),
    R2_ACCESS_KEY_ID: z.string().min(1).optional(),
    R2_SECRET_ACCESS_KEY: z.string().min(1).optional(),
    R2_BUCKET: z.string().min(1).optional(),
    R2_PUBLIC_BASE_URL: z.string().url().optional(),
    SMTP_HOST: z.string().optional(),
    SMTP_PORT: z.coerce.number().optional(),
    SMTP_USER: z.string().optional(),
    SMTP_PASS: z.string().optional(),
    SMTP_FROM: z.string().optional(),
    CRON_SECRET: z.string().optional(),
    SEED_ADMIN_EMAIL: z.string().email().optional(),
    SEED_ADMIN_PASSWORD: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_SITE_URL: z.string().url().default("http://localhost:3000"),
    NEXT_PUBLIC_COMPANY_NAME: z.string().default("Your Company"),
    NEXT_PUBLIC_COMPANY_SHORT_NAME: z.string().default("Your Co"),
    NEXT_PUBLIC_COMPANY_ADDRESS: z.string().default("Lagos, Nigeria"),
    NEXT_PUBLIC_COMPANY_PHONE: z.string().default("+234 800 000 0000"),
    NEXT_PUBLIC_COMPANY_EMAIL: z.string().default("hello@example.com"),
    NEXT_PUBLIC_WHATSAPP_NUMBER: z.string().default("2348000000000"),
    NEXT_PUBLIC_BANK_NAME: z.string().default("Example Bank"),
    NEXT_PUBLIC_BANK_ACCOUNT_NAME: z.string().default("Your Company Ltd"),
    NEXT_PUBLIC_BANK_ACCOUNT_NUMBER: z.string().default("0000000000"),
    NEXT_PUBLIC_GOOGLE_MAPS_EMBED_KEY: z.string().optional(),
  },
  experimental__runtimeEnv: {
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
    NEXT_PUBLIC_COMPANY_NAME: process.env.NEXT_PUBLIC_COMPANY_NAME,
    NEXT_PUBLIC_COMPANY_SHORT_NAME: process.env.NEXT_PUBLIC_COMPANY_SHORT_NAME,
    NEXT_PUBLIC_COMPANY_ADDRESS: process.env.NEXT_PUBLIC_COMPANY_ADDRESS,
    NEXT_PUBLIC_COMPANY_PHONE: process.env.NEXT_PUBLIC_COMPANY_PHONE,
    NEXT_PUBLIC_COMPANY_EMAIL: process.env.NEXT_PUBLIC_COMPANY_EMAIL,
    NEXT_PUBLIC_WHATSAPP_NUMBER: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER,
    NEXT_PUBLIC_BANK_NAME: process.env.NEXT_PUBLIC_BANK_NAME,
    NEXT_PUBLIC_BANK_ACCOUNT_NAME: process.env.NEXT_PUBLIC_BANK_ACCOUNT_NAME,
    NEXT_PUBLIC_BANK_ACCOUNT_NUMBER: process.env.NEXT_PUBLIC_BANK_ACCOUNT_NUMBER,
    NEXT_PUBLIC_GOOGLE_MAPS_EMBED_KEY: process.env.NEXT_PUBLIC_GOOGLE_MAPS_EMBED_KEY,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION || process.env.NODE_ENV === "test",
});
